[package]
name = "wayfarer"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.2", features = ["serde", "csr"] }
leptos_meta = { version = "0.2", features = ["csr"] }
leptos_router = { version = "0.2", features = ["csr"]  }
log = "0.4"
wasm-bindgen = { version = "0.2" }
gloo = "0.8.0"
console_log = { version = "0.2"}
console_error_panic_hook = { version = "0.1"}
js-sys = "0.3.61"
serde = "1.0.159"
serde_json = "1.0.95"

